"use client"

import { useRef } from "react"
import { Button } from "@/components/ui/button"
import { Download, FileDown } from "lucide-react"
import { useLocale } from "@/hooks/use-localization"

interface PdfExportProps {
  reportId: string
}

export function PdfExport({ reportId }: PdfExportProps) {
  const { locale } = useLocale()
  const isEn = locale === "en"

  const handleExport = async () => {
    const { default: jsPDF } = await import("jspdf")

    const doc = new jsPDF("p", "mm", "a4")
    const pageWidth = doc.internal.pageSize.getWidth()

    doc.setFont("helvetica", "bold")
    doc.setFontSize(18)
    doc.text("Floor Plan Issue Diagnosis", pageWidth / 2, 20, { align: "center" })

    doc.setFont("helvetica", "normal")
    doc.setFontSize(10)
    doc.setTextColor(100)
    doc.text("Problems only. No fluff.", pageWidth / 2, 28, { align: "center" })

    doc.setTextColor(0)

    try {
      const res = await fetch(`/api/analysis/${reportId}`)
      const report = await res.json()

      let yPos = 40

      if (report.problems && Array.isArray(report.problems)) {
        doc.setFontSize(14)
        doc.setFont("helvetica", "bold")
        doc.text("Key Issues", 14, yPos)
        yPos += 8

        report.problems.forEach((problem: any, i: number) => {
          doc.setFontSize(10)
          doc.setFont("helvetica", "bold")
          const text = `${String(i + 1).padStart(2, "0")}  ${problem.zone}`
          doc.text(text, 14, yPos)
          yPos += 5

          doc.setFont("helvetica", "normal")
          const lines = doc.splitTextToSize(problem.issue, 180)
          doc.text(lines, 20, yPos)
          yPos += lines.length * 4 + 2

          if (yPos > 270) {
            doc.addPage()
            yPos = 20
          }
        })
      }

      yPos += 5

      if (report.causalChain) {
        doc.setFontSize(14)
        doc.setFont("helvetica", "bold")
        doc.text("Root Cause Chain", 14, yPos)
        yPos += 8

        doc.setFont("helvetica", "normal")
        doc.setFontSize(10)
        const lines = doc.splitTextToSize(report.causalChain, 180)
        doc.text(lines, 14, yPos)
        yPos += lines.length * 4 + 5
      }

      if (report.bottomLine) {
        if (yPos > 250) {
          doc.addPage()
          yPos = 20
        }
        doc.setFont("helvetica", "bold")
        doc.setFontSize(12)
        doc.text(report.bottomLine, pageWidth / 2, yPos, { align: "center" })
      }

      // Footer
      doc.setFont("helvetica", "normal")
      doc.setFontSize(8)
      doc.setTextColor(150)
      doc.text("Generated by Perfect Home — Honest Floor Plan Diagnostics", pageWidth / 2, 290, {
        align: "center",
      })

      doc.save(`perfect-home-report-${reportId}.pdf`)
    } catch {
      console.error("PDF export failed")
    }
  }

  return (
    <Button variant="outline" size="sm" onClick={handleExport}>
      <FileDown className="mr-2 h-4 w-4" />
      {isEn ? "PDF" : "PDF"}
    </Button>
  )
}
